### ISSUE TITLE
FOSUserBundle exception

### ISSUE THREAD

**Issue by viniciuswebdev** [FriendsOfSymfony/FOSUserBundle#1062]
First, thanks for the project!

im getting this exception sometimes, but i cant simulate:

ErrorException: Warning: simplexml_load_file(): I/O warning : failed to load external entity "/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Resources/config/doctrine/User.orm.xml" in /vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php line 706

thanks!

**Comment by nserrar** [comment]
I'm having this bug in our dev server lately, it shows randomly, but not in prod. Nobody seems to have a solution for this, but you talking about it being fixed but how? changing vendor to 
XmlDriver.php Line 736
$xmlData = file_get_contents($file);
$xmlElement = simplexml_load_string($xmlData);

is not really an option, reinstalling libxml2 or updating didn't work neither.

Thanks for any input that may help.

**Comment by skonsoft** [comment]
I have the same probelm, but not in production environment.

Any solution ?

Thank you.

**Comment by KailZhang** [comment]
Run into this problem today. No idea why it turns up after running for more than half year.

**Comment by sgomez** [comment]
Well, I was searching for a solution and I concluded that the problem is the bug (or feature?) indicated by @matts2cant  two years ago: https://bugs.php.net/bug.php?id=64938

The function 'libxml_disable_entity_loader' is not thread safe so, if a thread configure it to 'true' all the others threads are true too. And it should be at 'false' by default when a new request come. That is why the problem disappears when we restart php-fpm daemon.  

If you write this at the beginning of app.php we can see that all is working again:

``` php
<?php
// app.php
libxml_disable_entity_loader(false);
```

The problem is caused by some third-party bundle or library, because it must be changing to true and is not restoring to false again.

**Comment by KailZhang** [comment]
@sgomez Good job. I think this is true.

**Comment by richard-keller** [comment]
I'm experiencing this problem too. As @sgomez correctly noted, the problem occurs when another thread sets libxml_disable_entity_loader(true). So if you have another app on the same server which sets libxml_disable_entity_loader(true), you'll eventually run into this problem.

In our case, the problem was caused by Phabricator. After restarting php-fpm, everything is fine until someone accesses Phabricator, which then sets libxml_disable_entity_loader(true), causing this error to occur in our Symfony app, due to thread sharing.

So there are 2 possible solutions:
1. Find out which app is setting libxml_disable_entity_loader(true), and move it onto another server, or,
2. In your web/app.php file, add the following code as suggested by @sgomez :

```php
<?php
// app.php
libxml_disable_entity_loader(false);
```

**Comment by layanto** [comment]
Having this issue too, on my server it is relating to tt-rss (https://tt-rss.org) on the same PHP server setting libxml_disable_entity_loader to true. To fix this, I changed line 814 of Doctrine's XmlDriver.php (doctrine\orm\lib\Doctrine\ORM\Mapping\Driver\XmlDriver.php)
from: $xmlElement = simplexml_load_file($file);
to:     $xmlElement = simplexml_load_string(file_get_contents($file));

Not sure how to raise issue in Doctrine's project to get this looked at.

**Comment by layanto** [comment]
Posted to doctrine-user Google+ group:
https://groups.google.com/forum/m/#!topic/doctrine-user/vAb_3zcz6vU
