### ISSUE TITLE
 Unknown column 't0.username_canonical' in 'where clause'

### ISSUE THREAD

**Issue by elmehdi-elmais** [FriendsOfSymfony/FOSUserBundle#1274]
hi ,

when i used same register in FOSUserBundle
i get this error i dont know from what

 i get this and SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username_canonical' in 'where clause'

**Comment by guglielmobossi** [comment]
In my opinion this issue is not closed.
I've the same problem, with the extension of a class that extends the FOSUser class.
In particular I've a problem in SyliusUser extension.

The error is SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.username_canonical' in 'where clause'

The query contains alias "t1" and not "t0".

The workaround that I've find is not extend the Sylius User class, but copy the class and add to it the code that I need... Very dirty solution :(

**Comment by stof** [comment]
@guglielmobossi if there is a bug when using the Sylius user class, this should be reported to Sylius, not to FOSUserBundle.

and btw, aliases are generated by Doctrine itself, not by us.

**Comment by AngeTunisienne** [comment]
@guglielmobossi I have the same problem can you help me pleeaaase

**Comment by krvajalmiguelangel** [comment]
I have the same problem when using SonataUserBundle
