### ISSUE TITLE
Not configured translate message for resetting.password_already_requested

### ISSUE THREAD

**Issue by zomberg** [FriendsOfSymfony/FOSUserBundle#1573]
This message include 24 hours:

```
The password for this user has already been requested within the last 24 hours.
```

But in FOS\UserBundle\Controller\ResettingController this message related with 'fos_user.resetting.token_ttl parameter:

``` php
if ($user->isPasswordRequestNonExpired($this->container->getParameter('fos_user.resetting.token_ttl'))) {
return $this->container->get('templating')->renderResponse('FOSUserBundle:Resetting:passwordAlreadyRequested.html.'.$this->getEngine());
}
```

Message text must depends on fos_user.resetting.token_ttl parameter.

**Comment by bschultz** [comment]
The passwordAlreadyRequested view got deleted in #2250 to not indicate user accounts.
So for me it seems the resetting.password_already_requested is now obsolete.

The token lifetime is actually supported in resetting.check_email but it only supports at least 1 hour and only whole hours due to this code: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ResettingController.php#L125

The problem is also that if one defined a token_ttl between 1 and 2 hours (e.x. 7000) the message will indicate that the user can request again in 1 hour.

So I have 2 questions before working on a PR:

- Should we indicate the exact time and show a ttl lower than 1 hour in the message?
- Or maybe just change here to use the ceil() function and show only the next larger hour?

**Comment by damienalexandre** [comment]
I think that's OK to display an approximation, and as `floor` is used for the ResettingController, that's may be the logic to keep in other places IMO.

**Comment by bschultz** [comment]
So you mean keeping the `floor` in ResettingController?

IMO currently there is a wrong approximation due to the usage of `floor`.
If one define a token_ttl lower than 3600 the message will be 

> ...new password within 0 hours. 

If the token_ttl is greater than 1 hour but lower than 2 hours the message will be

> ...new password within 1 hours. 

So I guess it will be "better" to use `ceil` ?

**Comment by damienalexandre** [comment]
Ok, I agree with you, let's switch to `ceil` :+1:

**Comment by steveWinter** [comment]
I agree that using ceil seems like the best approach - better to under-promise, and over-deliver
