### ISSUE TITLE
use_username_form_type doesn't seem to do anything?

### ISSUE THREAD

**Issue by eddiejaoude** [FriendsOfSymfony/FOSUserBundle#1716]
I would like to have the user's email when registering not username. The following config does not seem to disable the username requirement?

```
use_username_form_type: false
```

Or does this do something else?

**Comment by eddiejaoude** [comment]
Scrub that, I just came across https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/logging_by_username_or_email.md

I will give it a go :smile:

**Comment by eddiejaoude** [comment]
Unfortunately, it make no difference either?

```
providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
```

**Comment by eddiejaoude** [comment]
After following more links in various issues relating to the same issue, they all seem to refer to each  other & go full circle. 


There appears to be a few solutions. 

Is there a date when it will be resolved officially?

**Comment by Are-no** [comment]
I confirm this problem

<code>use_username_form_type: false</code>

not working

**Comment by ronanguilloux** [comment]
Some insight about `use_username_form_type`:

* It's [documented here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/form_type.rst)
* Its [default value is true](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/Configuration.php#L56)
* It's [actually used to call `username_form_type.xml`](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/FOSUserExtension.php#L101), which is a service configuration file that loads a [`UsernameFormType`](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Form/Type/UsernameFormType.php). Such `UsernameFormType` class exists to add a data transformer to the form process: It uses a [`UserToUsernameTransformer`](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Form/Type/UsernameFormType.php), that just get a username from a `UserInterface` object.

The fact is that adding (or not) such `DataTransformer` to a `FormType` actually does not make it using or avoiding such `username` field in the final form processing and rendering. Which makes the whole thing very unclear.

Renaming this parameter as `transform_username_in_form_type`, may eventually improve its comprehension.

So far, in order to change the way username/email are processed in forms, the best solution to me was overriding the vendor bundle (making him a parent of the new one), then overriding both entity & form in this new bundle, in order to make them act differently from the default FOS behavior. [A comprehensive solution guide may be found here](http://stackoverflow.com/a/21064627).

**Comment by stof** [comment]
@ronanguilloux use_username_form_type is just here to be able to disable the registration of the UsernameFormType.
It has strictly nothing to do with the registration form type.

**Comment by ronanguilloux** [comment]
@stof Sorry, I misunderstood the "registering" thing in the original question
