### ISSUE TITLE
register validation not works

### ISSUE THREAD

**Issue by OHoussein** [FriendsOfSymfony/FOSUserBundle#1755]
When I register with an existing email, in the registerAction RegisterController `$form->isValid()` returns true despite that there is a constraint that exists in Fosuserbundle but I got an DBALException (An exception occurred while executing 'INSERT INTO … ').

I created a bundle that inherits FOSUserBundle and MyUser entity inherits BaseUser and I ovverided the RegistrationFormType.

**Comment by stof** [comment]
When overriding the registration form type, which validation groups are you using to validate the user ? I suspect that you don't run the validation group in which FOSUserBundle puts the constraint.

**Comment by migueleliasweb** [comment]
I'm having the same problem. I'm currently starting a project with SF 2.6.6.

I have two entities: User who extends FOS's user and AdminUser who has OneToOne relation with User and has a bunch of extra fields.

I configured my config.yml with my User, but there's nothing I can do. The $form->isValid() returns true no matter what. I'm trully desperate.

@houssine91 Did you found how to fix this ? I really don't want to hard copy all fos validation to my bundle...

**Comment by migueleliasweb** [comment]
I solved partially the problem.

I put `'validation_groups' => array('Registration')` at the `setDefaultOptions` method of my AdminUserType and also put the same validation group at the UserType (form as a service).

With this I was able to achieve the correct validation from FOSUserBundle, but this made me use other  validation groups at the same time because of my specific validation for the entity.

My error was on my topmost form (AdminUserType) I did not had the correct registration group, so the child forms didn't get correctly notified  about the needed validation.

Hope this helps o/

**Comment by houssine91** [comment]
thank you @migueleliasweb  for your solution. For my issue, i fixed it by copying the file **validation.xml** in config directory and that work fine.

**Comment by migueleliasweb** [comment]
That's exactly what I was trying to avoid =/ (hard copying everything to my own bundle)

If you could check if my solution also fix for your problem, we could close this issue...

**Comment by XWB** [comment]
Closing as there is no better solution.
