### ISSUE TITLE
Can and Should I cache symfony2 getUser()

### ISSUE THREAD

**Issue by Don87** [FriendsOfSymfony/FOSUserBundle#1770]
I am using Symfony ( current version 2.6.4 ) whenever I want to check if a user is loggedin ( I am also using FOSUserBundle ) I use $user = $this->getUser(); in my controller which works out just fine but if I open 10 links in 1 second this query is repeated for all 10 pages in that second, not so ideal in my option. So my question is, is there a way to cache this query for say 60 seconds and is it even advisable, will it affect new registrations or something. I am using APC as my doctrine cache but if someone knows the answer please also tell us how to use other ways incase other people also wonder how to do this. Thanks. I have also posted this on Stackoverflow reference here

http://stackoverflow.com/questions/28830086/can-and-should-i-cache-symfony2-getuser

And a very similar question points to FOSUserBundle as the possible issue reference here

http://stackoverflow.com/questions/27608342/symfony2-fosuserbundle-not-using-usermanager-to-provide-cached-user-entity

**Comment by stof** [comment]
``$this->getUser()`` in your controller does not perform any Doctrine query (and it does not involve FOSUserBundle at all). It reads the user from the security context (or the new TokenStorage service in Symfony 2.6+ as the security context has been split). ``getUser`` is a simple getter.

The query loading the user happens in the security system itself, and caching it as very complex (which is why FOSUserBundle does not do it), because it would mean that the user being returned is not the managed entity anymore. See #66
