### ISSUE TITLE
Publish alpha2

### ISSUE THREAD

**Issue by KingCrunch** [FriendsOfSymfony/FOSUserBundle#1773]
I think it's time for an alpha2 :smile: alpha1 breaks with some recent changes in `doctrine/common`, see https://github.com/doctrine/common/pull/357#issuecomment-77956251

This issue was already fixed in September the 26th 2014 with https://github.com/FriendsOfSymfony/FOSUserBundle/commit/047b0e68ece4434dfc517819f1a103b84883b1da

**Comment by rande** [comment]
@KingCrunch it will be great to have a 2.0 release ;) @stof what are the missing bits ?

**Comment by KingCrunch** [comment]
One I can think of: Whether or not `FOSUserBundle` can unlink the `UserInterface` from Symfonys `AdvancedUserInterface`, see https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1751
That's in some cases a BC-break, so imo it should be before beta/stable. @stof Ping me, if I can do it :smile: 

@stof Is the [Milestone](https://github.com/FriendsOfSymfony/FOSUserBundle/milestones/2.0) issue list up to date?

**Comment by JHGitty** [comment]
Companies would like to use this bundle internally but dont like it because it has a dev/alpha status. Hope that there will be a stable release soon.

**Comment by tarjei** [comment]
@JHGitty the 1.3.x branch is very stable!

**Comment by JHGitty** [comment]
@tarjei Yes, but 2.0 too! A lot of people are using it in production environment, stof confirmed it here: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1852#issuecomment-109282915

**Comment by tarjei** [comment]
What do I have to do to upgrade, is there a rough guide somewhere?

2015-06-06 19:05 GMT+02:00 JHGitty <notifications@github.com>:

> @tarjei <https://github.com/tarjei> Yes, but 2.0 too! A lot of people are
> using it in production environment, stof confirmed it here: #1852
> (comment)
> <https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1852#issuecomment-109282915>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1773#issuecomment-109617873>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by Blackskyliner** [comment]
A Milestone + Issues which have to be solved for 2.0 to hit release would be awsome, this way contributers could concentrate on such tickets/problems und it would be easier to contribute "the right thing" to the goal.

@stof would it be possible to create such management within this current issue situation? Maybe line out some features there should be in for 2.0 (like the complete and correct usage of events instead of the old formhandler?), create a milestone add existing issues and maybe create some new ones so we can help out a bit better? - I know that because of 10 pages of issues, this question would be at least 1 days work, but then we could finally move forward with FOS, currently it "feels" much abondened, because only very few new commits, if any, pushing something forwards, are made.

**Comment by JHGitty** [comment]
@stof Please give us a chance to help you by adding all needed issues to the 2.0 milestone.

**Comment by Blackskyliner** [comment]
@XWB - As it seems that you currently manage this repository (or at least review and merge pull requests), any response on the stated questions/ideas would be really welcome.

**Comment by XWB** [comment]
I'll tag a second alpha very shortly.

We should define a roadmap for 2.0 afterwards.

**Comment by XWB** [comment]
v2.0.0-alpha2 is now available.

https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha2

**Comment by stloyd** [comment]
@XWB You should add note that `5.3.9` is now min. PHP version.

**Comment by stof** [comment]
Alpha2 should not be used. I reverted one of its change in alpha3
