### ISSUE TITLE
FOSUserBundle data shared across multiple Symfony2 Installs

### ISSUE THREAD

**Issue by Don87** [FriendsOfSymfony/FOSUserBundle#1794]
I am creating a social network using Symfony 2 and I have used FOSUserBundle among others. I have a main domain say mysite.com which has my Symfony2 install and code. I save sessions to a database using pdo. I have created separate subdomains where I wish to install separate Symfony2 with FOSUserBundle but I want to share a common user table and sessions. How is this possible? Thanks. Subdomains are like support, developers, etc and are hosted on different servers with different configurations and php versions.

My thinking is that if I can configure FOSUserBundle to use a separate database all together, than I can configure all my Symfony installs with FOSUserBundle to fetch and persist data to that database but I could be wrong. Any help, I am sure people must have encountered this before.

Stackoverflow reference : http://stackoverflow.com/questions/29372493/fosuserbundle-data-shared-across-multiple-symfony2-installs

**Comment by alexislefebvre** [comment]
This doesn't look like a valid issue, it seems that you're asking for support.

**Comment by stof** [comment]
Using a dedicated database is indeed an option. However this has a bunch of drawbacks:

- not possible to create relations to your data, because users are in a different DB
- storing sessions of different Symfony projects in the same table could break things (if they don't use the same version of Symfony for instance, or the same version of PHP)

A much cleaner solution is probably to use a single sign-on endpoint (which would store users, possibly using FOSUserBundle) and then making your other sites use the SSO endpoint to authenticate users.

Anyway, this is indeed not a FOSUserBundle issue, so I'm closing this ticket.
