### ISSUE TITLE
"Authentication request could not be processed due to a system problem."

### ISSUE THREAD

**Issue by JonnyD** [FriendsOfSymfony/FOSUserBundle#1807]
I can't figure out what the problem is. I followed the documentation and triple checked everything. I get this error message when I try to log in "Authentication request could not be processed due to a system problem."

**Comment by gpapin** [comment]
you have closed this issue does it mean you found the solution ? I have a similar problem, maybe you could help ?

**Comment by stof** [comment]
@gpapin when you have such an issue, you should check your logs. It generally means an exception happened and got logged

**Comment by gpapin** [comment]
I wish I could but my logs are empty. apache logs are only concerning access.log and more worrying, there is no prod.log in app/logs it's a fresh deploy to a new server using capifony, I've copied the setup I had from another working project but something is definitely wrong with it... (before you ask, yes apache can write to app/logs)

**Comment by xabbuh** [comment]
@gpapin Is the logs directory writable by the user which is running the web server?

**Comment by fpilee** [comment]
I'm having the same issue. I updated my vendors today(since like 9 months) on my dev machine, everything was okey. But in production I got thousands of files modified by FOSuserBundle and composer was asking about discarding changes, If I choose keep changes composer fails to update if I discard the changes composer finish the update. But then I cannot log in on my site, no messages on app/cache/prod.log. 

In my case it may be related due to bad upgrade process, cause my server does not have more than 512mb and composer update is killed, so I have to upload the composer.lock as some suggest on SO  
http://stackoverflow.com/questions/20667761/composer-killed-while-updating

To made work my site again, I reverted the update going back to the old composer.lock and executing composer install.
