### ISSUE TITLE
FosuserBundle - two authentication applications in the same browser

### ISSUE THREAD

**Issue by ghis31** [FriendsOfSymfony/FOSUserBundle#1836]
Hi,

I installed fosuserbundle and it works fine. My problem is, I have two aplications symfony on a single server and I can not authenticate on the two simultaneously in the same browser. When the user connects to an application, the second application user is automatically disconnected. But on two different servers you can connect even in a browser,

Please can - you help me to solve this problem, I wish I could connect me to both applications in the same browser.

Someone should - there a possible solution?

thank you

**Comment by stof** [comment]
This has nothing to do with FOSUserBundle, given that it does not deal with authentication at all.

I'm quite sure your issue is that you don't change the cookie name for the session, meaning that your projects are both using the same id, and so setting a session cookie in 1 project overwrites the cookie for the other project being accessible on the same domain.

**Comment by stof** [comment]
anyway, closing as this is not a FOSUserBundle issue

**Comment by ghis31** [comment]
Thks, I solve my problem. It was due to the session name like you say.
