### ISSUE TITLE
Embedded form other entity in fosuserbundle registration form

### ISSUE THREAD

**Issue by marshallus** [FriendsOfSymfony/FOSUserBundle#1892]
[Sorry for bad english]
Hi
I have an entity attached to fosuser by relation onetomany.
I want to add in the registration form the fields of this entity

Can you explain me the way to do this?

**Comment by Ingannatore** [comment]
First of all, you have to understand how embedding forms works in Symfony 2 (see http://symfony.com/doc/current/cookbook/form/form_collections.html); then you can check the official documentation to learn how to override FOS base forms: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_forms.md

**Comment by marshallus** [comment]
thank you, i was already looking this, but was thinking it was a bit complicated for me to achieve such a goal

**Comment by Ingannatore** [comment]
Yes, it surely seems to be a bit complicated at first but try to tackle one problem at a time; start by overriding the base FOS form by adding (for example) a single field and test it. Then, instead of embedding directly a one-to-many entity, try embedding one single entity into the FOS form and test it. And so on :)

A type can be as simple as a single field or as complex as an entire form; you can also [define your type as a service](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html#creating-your-field-type-as-a-service) and use it inside other types.

In my webapp I have an `Event` entity with one or more `DateRange` entities (one-to-many). I've defined my two types (`EventType` and `DateRangeType`); inside my `EventType` I have something like that:

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dates', 'collection', array(
                'type' => new DateRangeType(),
                'label' => 'label.dates',
                'allow_add' => true,
                'allow_delete' => true,
                'delete_empty' => true,
                'attr' => array(
                    'class' => 'collection-holder',
                    'data-not-empty' => 1
                ),
                'options' => array('label' => false)
            ));
    }
```

I've basically followed the [first guide](http://symfony.com/doc/current/cookbook/form/form_collections.html) I've posted.

**Comment by marshallus** [comment]
thank you for help, i already had put a single field and it's working as intented.
I 'm listening to you and now trying to embedded one single entity ;)

**Comment by Ingannatore** [comment]
Glad to be of any help, good luck with your work :)

**Comment by marshallus** [comment]
i'm trying to overrihe a controller without success 
i look here :
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_controllers.md
i have my bundle and create src/Acme/UserBundle/Controller/RegistrationController.php
Of course my bundle is a child of Fosuserbundle

And nothing appends, i mean symfony loads the original controller :/

**Comment by marshallus** [comment]
Clear the cache !
