### ISSUE TITLE
Restore Markdown docs

### ISSUE THREAD

**Issue by MaxArt2501** [FriendsOfSymfony/FOSUserBundle#1901]
[`Convert the doc to rST to be able to render it on symfony.com`](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/7523d11674568e39fa4b0023614de23acc72edfe)

So, instead of trying to get Markdown support on symfony.com, apparently *completely breaking* documentation navigation on GitHub (where people actually look for documentation) is a better idea.

Sounds marvellous, *if only FOSUserBundle's docs were actually on symfony.com.*

To be honest, I actually have no idea if they are, because no link is provided in the readme file, and symfony.com's search is down at the moment.

Can we get, at least, a Markdown version fo the documentation together with the rST version so people don't have the hassle to convert the documents by themselves?

**Comment by MaxArt2501** [comment]
Addendum: it looks like only index.rst can't be correctly rendered on GitHub.

In the end, it's not *completely* broken, but the index needs an alternative version.

**Comment by stof** [comment]
@MaxArt2501 docs will be on symfony.com very soon (as soon as @javiereguiluz completes the process as the last step is out of my control as I cannot change the symfony.com website itself).

**Comment by javiereguiluz** [comment]
@MaxArt2501 this documentation will soon been rendered on symfony.com, like we already do for [FosRestBundle docs](http://symfony.com/doc/master/bundles/FOSRestBundle/index.html), [KnpMenubundle docs](http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html) and [LiipImagineBundle](http://symfony.com/doc/master/bundles/LiipImagineBundle/index.html).

I just ask a bit of patience. Thanks!

**Comment by MaxArt2501** [comment]
That's great news!

But is there a chance to have an alternative version of the index, at least in the meanwhile?
I would be a matter of restoring index.md and changing the links at the end.

**Comment by stof** [comment]
@MaxArt2501 restoring index.md would mean having duplicate content for the doc and then havign to ensure they don't get out of sync. This seems a bad idea to me.

If you want the 1.3.x doc, just browse them in the 1.3.6 tag rather than in the branch: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v1.3.6/Resources/doc/index.md
If you want to have the 2.0.x doc, you can browse it at https://github.com/FriendsOfSymfony/FOSUserBundle/blob/17de762cb6da7f6b3f5eca7795d7a3550786ea83/Resources/doc/index.md for now (i.e. just before the conversion to rST)

@javiereguiluz do you know when it will be rendered on the site ?

**Comment by javiereguiluz** [comment]
@stof I don't know, but I'm on it.

**Comment by ekonoval** [comment]
Maybe for newcommers like me the new link would be useful http://symfony.com/doc/master/bundles/FOSUserBundle/index.html

**Comment by stof** [comment]
@ekonoval the link only works since a few hours. I have not yet updated links to the doc in the readme

**Comment by xabbuh** [comment]
see #1909 and #1910

**Comment by stof** [comment]
Fixed in f22f8e37bc76c346c55f39338617ba136a84d1f9
