### ISSUE TITLE
Doctrine user class example is not showing up on github

### ISSUE THREAD

**Issue by mantuko** [FriendsOfSymfony/FOSUserBundle#1911]
Hi,

I'm just starting with Symfony and it's the first time I encountered reStructured Text but as the title says the example for the doctrine user class is not showing up in the documentation on github.

If I view the index.rst file in an editor I see the example in PHP, YAML and XML but it's not showing up on Git Hub. Which is the place where most people especially beginners like me view it. As I'm new to reStructured text and the way Git Hub renders it I've got no how to fix this. Sry.

Thanks, mantuko

Update:
Same with the fos_user config example in step 5.

**Comment by stof** [comment]
The doc is now available on http://symfony.com/doc/master/bundles/FOSUserBundle/index.html, which is why it was converted to rST (and uses some features unsupported by the Github preview). I haven't updated the doc link in the readme yet (having the doc rendered online took a few days after I completed the conversion as it required waiting until the next deployment of the website)

**Comment by stof** [comment]
Link is fixed in f22f8e37bc76c346c55f39338617ba136a84d1f9
