### ISSUE TITLE
Why the delay with stable 2.x release?

### ISSUE THREAD

**Issue by redactuk** [FriendsOfSymfony/FOSUserBundle#2067]
Version 2 has now been in Alpha since Sep 14, which is an incredibly long time! Not having having a stable v2 is now causing a serious bottleneck with the further development of other applications e.g Sonata - that still has to rely on v1.3. We were promised stable v2 'this coming weekened' back in December, but 2 months later still nothing. I appreciate everyone in this community has other commitments, but please please can a stable v2 of this bundle be made a priority. I'm fairly new to Symfony but I've already found a huge number of projects and discussions related to having to find 'workarounds' for this longstanding issue of there not being a stable v2. Furthermore, for a bundle actualy documented and supported on main Symfony site, I find it even stranger that this bundlle has been allowed to get so far behind and be the cause of so many issues. Again, can you guys please make a stable v2 a priority so that other dependent apps can move forward. Thank you.

**Comment by 1ed** [comment]
I would ask instead how can we help? @stof there is a todo list? The [2.0 milestone](https://github.com/FriendsOfSymfony/FOSUserBundle/milestones/2.0) is still relevant?

**Comment by luispabon** [comment]
Indeed, how can we help? Plenty of other projects cannot unfortunately support S3 until this bundle has a stable compatible release.

**Comment by redactuk** [comment]
@stof please could we have an update on this? You and rest of developers have done an awesome job to date on this Bunble and I 100% appreciate you may want to focus on other stuff right now, but could you at least spare a few hours to update the roadmap? perhaps most of very old entries with no progress could be flagged for a 2.1 leaving just the urgent ones for others to help with?

**Comment by ahundiak** [comment]
Conspiracy alert!  Cue the X-Files music.

Development of the event driven 2.x version actually started Aug 31 2012.  Three and half years ago as of this writing.  Six months since the alpha release is bad but three and a half years?

It's not a case of volunteer development support.  If you go through the issues you can see this sort of post coming up time and time again.  Requests for a release road map are met with silence or a vague "working on it".  Myself and quite a few other people would be happy to help clear the issues if only we knew what they were.

I had hoped that the 2.8/3.0 might kick start things but sadly no.  Sure there a development version that works but every time you do an update your risk a breakage.  In fact that is what made me abandon the bundle for my own apps a few years ago.  No stability on the master branch and using the old S2.1 version just seems wrong.

It is hard to write this without coming across as being critical.  That is certainly not my intention.  I have the utmost respect for the original developers and I know how busy they are and how much they have contributed.

Still, three and a half years of silence on what is by far the most widely used 3rd party bundle just seems excessive.  Maybe it is something in the water?

**Comment by luispabon** [comment]
Maybe fork? No reason not to, being oss.

**Comment by luispabon** [comment]
Bundle could do with removing s2 compat entirely, bc is undoubtedly holding it back for a stable release.

**Comment by fcpauldiaz** [comment]
I agree with @luispabon. The community should start searching for people to maintain a new fork.

**Comment by wodka** [comment]
:) please

**Comment by luispabon** [comment]
I don't really have the time to fully maintain a fork, but if someone else
takes the initiative I can help Squashing bugs and cleaning up s2 bc

**Comment by Zeichen32** [comment]
Maybe we can organisate a Hacking Day like:
http://symfony.com/blog/symfony-docs-hack-day-needs-you-on-may-23rd

**Comment by ahundiak** [comment]
I went ahead and created a repo at: https://github.com/cerad/FOSUserBundle3

This is not a fork.  It's empty at this point.  The idea is to come up with a road map for releasing a stable version specific to Symfony 3.  What would be nice is if people would work their way through the current issue list and help determine which if any need to be fixed for 3.x.  Or if there is anything else that people strongly feel should be added to an S3 version.

Hopefully we can feed the results of the discussion back into here.

**Comment by trousers** [comment]
I would like to help out but there hasn't been any progress for a while. Is a road map in development?

**Comment by eduardoconceicao** [comment]
I'm here to help as well. Where should i start?

**Comment by robertfausk** [comment]
Also take a look at related issues https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1996 and https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1951

It seems that the maintainers can not afford enough time. There is already a roadmap but no progress or response at all.

**Comment by tim96** [comment]
@stof Hello. Do you have a todo list for version FOSUserBundle 2.0? Can I help you to finish it?

**Comment by danielkay** [comment]
So I'm guessing this bundle has been abandoned then... shame, considering the community are evidently so keen to help fix the issues if there were only a roadmap. Symfony should probably remove references to FOSUserBundle from the documentation as there is no longer any support.

**Comment by tuxayo** [comment]
@danielkay It's much harder to find maintainers than contributors. It's a kind of tragedy of the commons.

**Comment by core23** [comment]
Any news on this? @stof @XWB 

Why the delay for a final release? Anything to do here? Can we help to keep this project moving forward?

**Comment by OskarStark** [comment]
@core23 I think reviewing PR's and issues in the [2.0 Milestone](https://github.com/FriendsOfSymfony/FOSUserBundle/milestone/4) would help

**Comment by XWB** [comment]
Closing this in favor of https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2206
