### ISSUE TITLE
Symfony 3 Support

### ISSUE THREAD

**Issue by bretanac93** [FriendsOfSymfony/FOSUserBundle#2070]
Hi, there isn't any official branch for symfony 3?, cause when I'm trying to install the bundle, there are some issues that doesn't allow me to make a clear installation.

**Comment by 1ed** [comment]
The master branch is compatible, but there is not stable release yet... use `~2.0@dev`, `dev-master` or `dev-master#e770bfa` in your composer.json.

**Comment by Pierstoval** [comment]
Let's add a :+1: here because FOSUserBundle's last 2.0 alpha still requires security-bundle `~2.3` and we can only install FOSUserBundle `dev-master` on a Symfony 3 app.

**Comment by danielcotton** [comment]
`~2.0@dev` now works. Tested on Symfony 3.0.4

**Comment by smokarz** [comment]
what is the reason of silence about stabile version ? @stof could you please write any answer ? I am following all subjects about FOS User Bundle and cant see any information about that. Many people ask how they can help to solve any problems with User bundle to be done. Now its only one reason of using Symfony 2.7 because its hard to use FOS dev version on prod env of my project.

**Comment by suncat2000** [comment]
+1
Stable 2.0 version of this bundle with support of sf3 is needed!

**Comment by XWB** [comment]
Will release a new alpha very shortly.

**Comment by Pierstoval** [comment]
👍
