### ISSUE TITLE
Symfony 2.3 and orm mapping 

### ISSUE THREAD

**Issue by fabgg** [FriendsOfSymfony/FOSUserBundle#2102]
I did and composer update  "Updating friendsofsymfony/user-bundle dev-master (e770bfa => 16b04c4)"
After I can't login in my app !!  Doctrine schema update command want to drop the fields ownered by FOSBU to User Table.
After analyse the comit 08f6481 dropped the mapping needed for 2.3 version.
use Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass; is undefined in Symfony 2.3.39

**Comment by stof** [comment]
``Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass`` is not a class coming from Symfony, so it has nothing to do with Symfony 2.3.39.

Use the latest version of DoctrineBundle instead of an outdated version, and you will get this class (latest version of the bundle is compatible with Symfony 2.3.39)

**Comment by fabgg** [comment]
Ok but i updated my app with comoser ! Please read the first part of the message !
