### ISSUE TITLE
FOSUserBundle upgrade for symfony3

### ISSUE THREAD

**Issue by mirbahar** [FriendsOfSymfony/FOSUserBundle#2127]
need to be FOSUserBundle symfony3

**Comment by stof** [comment]
The 2.x version of FOSUserBundle (the master branch) fully supports it, but it is not released yet

**Comment by Soullivaneuh** [comment]
@stof Symfony 3.1 is nearly here and no fos-user 2.0 stable for now.

I know you are doing your best, but lot of people can't upgrade to SF 3.0 because of this.

My question is: Did you always accepting PR against 1.3? One to support both SF 2.x and 3.x for example. This would be a good thing waiting the next major stable IMHO. :+1:

**Comment by covex-nn** [comment]
I have fixed 1.3.x code to make `friendsofsymfony/user-bundle` compatible with Symfony3. See #2167

**Comment by maZahaca** [comment]
Hi guys,
I'm also expecting to get 3.0 support. Do you have any plans on release it in the future?

**Comment by XWB** [comment]
Closing this in favor of https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2206
