### ISSUE TITLE
Method in Controllers to add extra view data to a view

### ISSUE THREAD

**Issue by playr1983g** [FriendsOfSymfony/FOSUserBundle#2146]
It would be nice if controller actions (especially show/view actions) had a method to enhance the view data.

I think most of the basic templates in this bundle will be overridden with own templates.

For example, in my custom templates there is often the need of extra view data (for example contact address in the footer)

Assume i want to add this contact data views to my ProfileController::showAction:

```
    /**
     * Show the user
     */
    public function showAction()
    {
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }
        return $this->render('FOSUserBundle:Profile:show.html.twig', array(
            'user' => $user  // <--------------------------------------------
        ));
    }
```

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ProfileController.php#L34

It would be nice if there was an template method to extend the view data, like this:

```
    /**
     * Show the user
     */
    public function showAction()
    {
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }
        return $this->render('FOSUserBundle:Profile:show.html.twig', array(
            'user' => $user, 'view' =>  $this->getShowViewData()  // <--------------------------------------------
        ));
    }

    public function getShowViewData()
    {
        // ...
       return ['contactData' => $contactData];
    }
```

The benefit of this: It's possible to add view data for my custom template without overriding the showAction() controller logic. 
Futures fixes or enhancements of the showAction() would automatically work without changes in my custom code. This would also be 100% backwards compatible.

Custom **x** profile templates need "user"  + **x** view data.

**Comment by rgutknec** [comment]
I would also be interested in the manner we can add a variable to templates?
Need to override controllers for that?

**Comment by rgutknec** [comment]
Ok, I just need to override `renderLogin` method in `SecurityController` if I want to pass extra data to login view, for example...

**Comment by XWB** [comment]
This has been discussed in the past, overriding the controller is the way to go.

**Comment by Laurent3170** [comment]
@XWB sorry to "re-open" this, but I have the same need.
I am overriding templates and need to send extra-data. For example in `showAction` I must overwrite the Controller. From here, I have two choices:
1) Copy/paste from the parent action as I can't use `parent::showAction()` because it renders the form, which cannot be achieved, because my data is not sent. By doing so I will lose everything added to this Action in the future, which is bad.
2) Load the user and assign it a property like below. Then in my template I can use `app.user.useGravatar`. The bad things are that the user is loaded twice and that the whole website parameter is assigned to each user, which should not be the way to do.
```
public function showAction()
{
    $user = $this->getUser();
    if ($user !== null) {
        $user->setUseGravatar($this->getParameter('bundle_name.gravatar'));
    }

     return parent::showAction();
}
```
But... I have found that in the [SecurityController](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/SecurityController.php) the `renderLogin()` has everything to avoid that!
We can override the `renderLogin()`, set the data we need and call the parent Action.
```
protected function renderLogin(array $data)
{
    $data = array(
        'gravatar' =>$this->getParameter('bundle_name.gravatar'),
    );

    return parent::renderLogin($data);
}
```

So my suggestion(question) is can't we do this for all actions that render a template? I know that it will give a big BC Break as everyone who has already overriden the Controllers must add this `array $data`.

Or, maybe there is a simpler solution to achieve what needed.

**Comment by Laurent3170** [comment]
Or, even better as it avoids the BC Break, do the following in each Controller add the function `setUserData()`
```
/*
 * Function to override to send data to the template
 */
public function setUserData()
{
    return array();
}
```
Update the rendering part
```
return $this->render('@FOSUser/Profile/show.html.twig', array(
    'user' => $user,
    'data' => $this->setUserData(),
));
```
Then we can just overwrite this function in our Controller
```
public function setUserData()
{
    return array(
        'gravatar' => $this->getParameter('c975_l_user_files.gravatar'),
    );
}
```
And then in the Twig template use `{% if data.gravatar == true %}...{% endif %}`

I think it doesn't cost anything and I can prepare the PR, no?

**Comment by Laurent3170** [comment]
I have created the PR #2587 If it's ok I will put an explanation where needed in the docs files
I had created one function per rendering template.
