### ISSUE TITLE
Release alpha4

### ISSUE THREAD

**Issue by exchentrix** [FriendsOfSymfony/FOSUserBundle#2206]
Hey,

thanks for this awesome bundle. Would it possible, that you release alpha4? Alpha3 is from late 2015 and I dont want to use dev-master.

Best,
Christian

**Comment by XWB** [comment]
I will work on that in the coming weeks.

**Comment by Pierstoval** [comment]
@XWB What's the situation for now? 😄

**Comment by Pierstoval** [comment]
@XWB, all other contributors, I don't know, @stof, @Ener-Getick, anyone, come on, I know I'm quite pushing you, but last alpha was released **more than a year ago**, and actual master branch is perfectly fine for 99% apps.
 
I see you are merging some pull requests, do you need help in creating the changelog for the alpha release? If you need help just ask contributors, everyone here wants a new release of the most famous Symfony bundle, especially since SF3 has been released for almost a year.

Community (me included if you like) will be really pleased to help you in releasing this new version, and don't mind bugs or anything, there are patch versions for this, and everyone will be happy.

No offense, I just think it's better to help everyone have a good composer dependency tree with no silly constraint like `dev-master` in it.

Just one single release for `2.0.0`

**Comment by Ener-Getick** [comment]
@Pierstoval i completely agree with you,.
Unfortunately, i'm not a regular contributor to this bundle and i don't know what are the current projects/aims so i can't release a new stable version myself without taking the risks of breaking them (maybe we're waiting for a new feature or a bug fix i don't know).

If @stof agrees (he's the last in charge if i'm not wrong?) I can of course take a look at the pending PRs/issues and then release 2.0.

**Comment by rjd22** [comment]
@Ener-Getick it would be okay if it was an alpha release I think. Doesn't have to be stable.

**Comment by Pierstoval** [comment]
@Ener-Getick Actually as said, at least an `alpha` release is fairly enough and does not imply generating a big changelog (because the changelog gets bigger and bigger in time).

Releasing `2.0.0` is a much harder task because we have to explain users what changed since `1.x`, and as I said, the community will be happy to help writing a big exhaustive changelog for `2.x` :)

**Comment by XWB** [comment]
@Pierstoval I think we can tag a new alpha when the last 4 PR's have been merged, see https://github.com/FriendsOfSymfony/FOSUserBundle/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.0

**Comment by crmpicco** [comment]
:+1: for a 2.0.0 release

**Comment by pdoreau** [comment]
I'm moving from SF 2.8 to 3. Is the alpha3 version stable enough for an app in production ?

**Comment by Pierstoval** [comment]
@pdoreau alpha3 is not compatible enough with SF3, you'll have to either wait for alpha4 ( ping @XWB 😄 ) or use `dev-master` and implement integration tests to be sure everything works well

**Comment by pdoreau** [comment]
Sure, a stable release would indeed be more than appreciated. I guess many developers don't wanna rely on an alpha dependency.

**Comment by Pierstoval** [comment]
@pdoreau you can help by reviewing all [2.0 milestone PRs](https://github.com/FriendsOfSymfony/FOSUserBundle/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.0) and it'll make things advance much faster 😉

**Comment by XWB** [comment]
We still have one outstanding PR https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1956

Will try to work on it asap.

**Comment by tgalopin** [comment]
Now that it's merged, is a release possible?

**Comment by lbayerl** [comment]
Is there anything we can support you to release 2.0.0? E.g. support in documentation, upgrade, examples, ...?

**Comment by XWB** [comment]
Before we do so, I have three questions:

- Does @stof has some breaking changes he wants to be merged in this release?
- What to do with Propel, it may have been fixed in https://github.com/symfony/symfony/commit/59f99493f8395e85cf175a8f888a22e5a3517ed1 but I cannot test it.
- Are we happy with names of the newest [events](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/FOSUserEvents.php) added in master?

Ideally we have all breaking changes in alpha 4 so we can works towards the first beta. If not, we may need another alpha release.

**Comment by Pierstoval** [comment]
> Regarding Propel, I'm all for removing it from FOSUserBundle itself, as it causes too much issues.

I'm totally 👍 👍 👍 👍 👍 for this 👏

**Comment by XWB** [comment]
I just merged https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2309 so Propel support is now gone in the latest master branch.

If @stof sends his remaining PR's, we can tag the next release.

**Comment by stof** [comment]
@XWB remaining blocker for the release: figuring out why one of the jobs fail on Travis in the master branch (I don't want to release with a red build)

**Comment by XWB** [comment]
@stof Well https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2319 seems to fix it, I'm not sure why.

**Comment by XWB** [comment]
@stof Master branch is green again, we are good to go.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-beta1

**Comment by lbayerl** [comment]
Thank you so much!

**Comment by Pierstoval** [comment]
Awesome 👏 👍 🎉

**Comment by OskarStark** [comment]
Great work @XWB 👏

**Comment by exchentrix** [comment]
Thank you very much! 👍

**Comment by samayo** [comment]
So, I have been reading these comments, and need to make sure. Is 2.0.0 compatible with Symfony 3.x? I have 3.2 and not sure what if I can use this bundle without problems.

**Comment by Tomsgu** [comment]
It is compatible with symfony 3.x. The only problem is that 2.0.0 is still in beta so you should be aware of it and probably will be in beta still some time (months?).

**Comment by Pierstoval** [comment]
@Tomsgu Years? 2.0.0 is "ready" to me, but as I'm not a contributor/maintainer I can't judge about what's been decided internally about 2.0 milestones (except for #2378 which is not yet finished)

**Comment by Tomsgu** [comment]
@Pierstoval No I am not judging here. I think it's important to know that it's still "unstable", so people should be careful when using it in production. Btw. I use it in production for months as well.

**Comment by Pierstoval** [comment]
Same for me, and my tests have never regressed even when I was using dev-master (actually they did, but for very little things, and was not breaking the app itself, and could fix this before deploying easily).

For my students I always recommend `2.0@beta` tag to be sure they get the "almost-stable" version

**Comment by samayo** [comment]
Thanks @Tomsgu @Pierstoval I installed it using `2.0@beta` and registed it in the bundle, but (shameless plug) I get this error when I tried to generate entities: 
> The child node "db_driver" at path "fos_user" must be configured. 
does anyone have any idea where this db_driver param is found?

**Comment by stof** [comment]
@samayo please don't comment on old unrelated closed issues to ask for support. It does not make your question discoverable.
and the doc explains this param: http://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle

**Comment by Pierstoval** [comment]
@samayo Yes: in FOSUserBundle's documentation  https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle

**Comment by samayo** [comment]
@stof Initially I was not sure if 2.0.0 supported Sf3 that is why I asked. About the error, I read the same doc you linked and [it didn't work](http://stackoverflow.com/questions/18913809/trying-to-install-fosuserbundle-but-getting-error#comment61658150_18914184) and I had to ask

**Comment by stof** [comment]
@samayo your previous comment talks about generating entity. the doc of the bundle **never** ask to use the entity generator.
