### ISSUE TITLE
Bundle works unexpectedly after enabling Symfony HTTP Cache

### ISSUE THREAD

**Issue by NovikovViktor** [FriendsOfSymfony/FOSUserBundle#2239]
Hello,
I have faced with a strange issues related to log-in/logout functionality after enabling HTTP Cache.
E.g. when I log-in to the system, and then push to logout button, after refresh I am still authenticated.
This issue occurs on environment with php7 and on another machine with php5.6 everything works just fine. I am not sure that php version could impact on this.
I tried to find related issues, but didn't get any results. When I turn off HTTP Cache - everything works as it should work.
Can somebody help me with this? Could FOSUb be used along with HttpCache?

Regards.

**Comment by ethernal** [comment]
I am experiencing the same thing on Sf 2.8.x and php 5.6 and 7.

Did you manage to find a workaround? ..or...How an I invalidate the cache )or force revalidation of page on logout/login?)

**Comment by stof** [comment]
the login and logout features are not provided by FOSUserBundle but by Symfony's SecurityBundle. So I'm closing this issue as it is not related to the bundle.

And when using HTTP caching, you need to be careful about including the right ``Vary`` header if you want to have different versions of your cached content depending on the authentication. Otherwise the same cache will be served to everyone.
Btw, you can have a look at FOSHttpCacheBundle if you want to be able to share the cache between authenticated users sharing the same permissions. But please read about how HTTP caching works first before going to such advanced features.
