### ISSUE TITLE
Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::__construct() must be an instance of FOS\UserBundle\Util\PasswordUpdaterInterface, instance of appProdProjectContainer given

### ISSUE THREAD

**Issue by ozzmaster** [FriendsOfSymfony/FOSUserBundle#2287]
This is the full error, paths anonymised:
[Sat Oct 22 11:58:03.741667 2016] [fcgid:warn] [pid 3508] [client 197.88.153.18:50868] mod_fcgid: stderr: #1 /~/var/cache/prod/appProdProjectContainer.php(1433): FOS\\UserBundle\\Doctrine\\UserListener->__construct(Object(appProdProjectContainer))
[Sat Oct 22 11:58:03.741669 2016] [fcgid:warn] [pid 3508] [client 197.88.153.18:50868] mod_fcgid: stderr: #2 /~/vendor/symfony/symfony/src/Sym in /~/vendor/friendsofsymfony/user-bundle/Doctrine/UserListener.php on line 34

Using Symfony3.

What do I need to do to fix this?

**Comment by xabbuh** [comment]
This is due to the changes made in #1615. Did you clear the cache after upgrading the bundle?

**Comment by ozzmaster** [comment]
I did not. Thanks for the prompt response! Closing issue.

I will now update my scripts to clear the var/cache/ folder with rm.

**Comment by lemzo63** [comment]
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::__construct() must be an instance of FOS\UserBundle\Util\PasswordUpdaterInterface, instance of appProdProjectContainer given, called in C:\wamp\www\Symfony\var\cache\prod\appProdProjectContainer.php on line 624 in C:\wamp\www\Symfony\vendor\friendsofsymfony\user-bundle\Doctrine\UserListener.php on line 34

i have this error because i just up garte to symfony 3.3.2 when i clear the cache for dev , no probleme but when i clear the cache for prod yhis error appears. 
who can help me please?
