### ISSUE TITLE
Is the documentation for 1.3 wrong ?

### ISSUE THREAD

**Issue by leogout** [FriendsOfSymfony/FOSUserBundle#2288]
Hi, I've been trying to use events with v1.3.6, which are described [here](http://symfony.com/doc/current/bundles/FOSUserBundle/controller_events.html).
However, the 1.3.6 (which is part of 1.3.x of the doc, right ?) doesn't seem to have any `FOS\UserBundle\FOSUserEvents` class...

Am I missing something ?

**Comment by XWB** [comment]
Must be a bug on the Symfony website, the 1.3 branch does not contains this file.

**Comment by XWB** [comment]
Ping @javiereguiluz

**Comment by javiereguiluz** [comment]
Yes, it's a problem on our side. I can't fix this at the moment ... but it's at the top of my list when changes are allowed again for symfony.com. I'm sorry and thank you for your patience.

**Comment by generalis** [comment]
When in FOSUserBundle 1.3.x will be available FOSUserEvents Class?

**Comment by stof** [comment]
never. The 1.3.x version of the bundle does not dispatch events in the controller. This is a feature of the 2.0 version (currently in beta 1)

**Comment by stof** [comment]
@javiereguiluz do you have any idea when this can be fixed ?

**Comment by javiereguiluz** [comment]
I'm sorry it took me so long to fix this. The cause of this problem was a bit tricky. When building the docs, we weren't "symlinking" `current` to the real version but to `master`. I think I've solve it for good now. I've sent a pull request and once merged and deployed, everything should work again.

Note: in this particular example, the solution will make the `http://symfony.com/doc/current/bundles/FOSUserBundle/controller_events.html` URL to return a 404 error, because that page should have never existed (`http://symfony.com/doc/master/bundles/FOSUserBundle/controller_events.html` will keep working, of course).

**Comment by XWB** [comment]
Thank you @javiereguiluz
