### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by mathiasmondofute** [FriendsOfSymfony/FOSUserBundle#2292]
Hello, I just did an update of fosuser via "composer update " in my Symfony2 project and since then I have this error occurred, it could someone get me out of this problem? Thank you in advance.

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must implement interface FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given, called in /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Doctrine/UserManager.php on line 47 and defined" at /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php line 46 {"exception":"[object](Symfony\Component\Debug\Exception\ContextErrorException%28code: 0%29: Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct%28%29 must implement interface FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\EncoderFactory given, called in /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Doctrine/UserManager.php on line 47 and defined at /home/mondofutedev.com/domains/crm-preprod.mondofutedev.com/public_html/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php:46)"} []

**Comment by XWB** [comment]
You need to change the `UserManager`, see https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md

**Comment by lemzo63** [comment]
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::__construct() must be an instance of FOS\UserBundle\Util\PasswordUpdaterInterface, instance of appProdProjectContainer given, called in C:\wamp\www\Symfony\var\cache\prod\appProdProjectContainer.php on line 624 in C:\wamp\www\Symfony\vendor\friendsofsymfony\user-bundle\Doctrine\UserListener.php on line 34

i have this error because i just upgrate to symfony 3.3.2 when i clear the cache for dev , no probleme but when i clear the cache for prod this error appears.
who can help me please?

**Comment by lemzo63** [comment]
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::__construct() must be an instance of FOS\UserBundle\Util\PasswordUpdaterInterface, instance of appProdProjectContainer given, called in C:\wamp\www\Symfony\var\cache\prod\appProdProjectContainer.php on line 624 in C:\wamp\www\Symfony\vendor\friendsofsymfony\user-bundle\Doctrine\UserListener.php on line 34

i have this error because i just upgrate to symfony 3.3.2 when i clear the cache for dev , no probleme but when i clear the cache for prod this error appears.
who can help me please?

**Comment by mhnrm** [comment]
Probably @lemzo63 solved that issue already for himself, but for anybody coming by with the same problem: 
I was able to fix it by radically deleting `app/cache/prod`.
