### ISSUE TITLE
I can't believe how hard is to embed a login form with a CSRF for a beginner/average developer

### ISSUE THREAD

**Issue by charafsalmi** [FriendsOfSymfony/FOSUserBundle#2335]
I just wanted to embed a login form in my header. I thought doing it by writing the html in my twig is the easiest way.

I tried this : http://stackoverflow.com/questions/8040512/fosuserbundle-embedding-the-login-form-and-choosing-its-template

I got "The service twig has a dependency on a non-existent service "form.csrf_provider"."

I tried this : http://stackoverflow.com/a/35777023/2058672

Changed nothing. Got a new "Impossible to invoke a method ("getToken") on a string variable ("security.csrf.token_manager") in base.html.twig at line 35." error.

I tried this : {{ render(controller('FOSUserBundle:Security:login')) }}

Rendered the same page as the /login route...

I tried overriding SecurityController : it messes up everything...

Is there any **recent** tutorial helping on this ?

Thank you.

**Comment by XWB** [comment]
Calling `{{ render(controller('FOSUserBundle:Security:login')) }}` is fine, you need to overwrite the login template as defined in http://symfony.com/doc/current/templating/overriding.html

**Comment by slaci** [comment]
It is not possible out of the box. You must override the SecurityController and redefine the `renderLogin()` function.

Overriding the controller: https://symfony.com/doc/master/bundles/FOSUserBundle/overriding_controllers.html

Redefining the `renderLogin` function in your own controller (like `AppBundle\Controller\SecurityController` if your AppBundle has `getParent() => 'FOSUserBundle'` function from the Overriding the controller part):
```php
namespace AppBundle\Controller;

use FOS\UserBundle\Controller\SecurityController as BaseSecurityController;

class SecurityController extends BaseSecurityController
{
    protected function renderLogin(array $data)
    {
        $template = null === $this->get('request_stack')->getParentRequest()
            ? 'FOSUserBundle:Security:login.html.twig'
            : 'embedded_login_form.html.twig'
        ;
        
        return $this->render($template, $data);
    }
}
```
This way when you use the suggested `{{ render(controller('FOSUserBundle:Security:login')) }}` then your template will be used, otherwise the default.
(Why? Because render controller creates a subrequest, and then you will have a ParentRequest, otherwise no)

This is the cleanest way for your problem I think (ofc not the only).
