### ISSUE TITLE
New registration email confirmation link produces 404 error if clicked more than once

### ISSUE THREAD

**Issue by djardine** [FriendsOfSymfony/FOSUserBundle#2371]
**Describe the feature**:

This is more of a feature request rather than a bug (unless this is in fact a bug that I'm seeing). We're getting a lot of users complaining that the account confirmation link in the new account registration confirmation email is leading them to a 404 page error. As far as I can tell, what's really happening is that they're clicking the link more than once (I'm really just theorizing here since I don't know for sure) because when I check their account status in our database the "enabled" column has been set to "true" which indicates that they did successfully follow the link. It seems that the first click to the link enables the account as expected, but successive clicks send them to a 404 page because the "confirmation_token" has been removed from the db table. This isn't an ideal user experience based on the number of confused customer emails we're receiving (for whatever reason they're not attempting to actually test out their account login on the site). Ideally once the confirmation link has been successfully clicked, successive clicks should send them to a page that says something along the lines of "Account has already been confirmed" or possibly just the fwd them to the same initial account validated page. It looks like this would require some rework on the db side as the confirmation token would have to be retained even after the link is initially clicked.

**Comment by stof** [comment]
Well, remembering that the confirmation link worked in the past would require keeping the confirmation token around (to distinguish from a non-existent link), and these are unique tokens btw.
It complicates things seriously.

Thus, FOSUserBundle reuses the same DB field for tokens used in the password resetting.

**Comment by djardine** [comment]
Ya that's right. Would it be possible to send the user ID or username in the confirmation link that way the backend can check if that user is already enabled and report that even if the token is no longer in existence?

**Comment by Laurent3170** [comment]
@djardine You may have a look at #2106 as it avoids this 404 redirection

**Comment by kapowkimc** [comment]
I received quite a few emails from users getting a 404 when trying to confirm a new account. After investigating the access_logs it turns out that useragent BingPreview/1.0b, is confirming the account before the user. So outlook webmail creates a preview thereby confirming the account and leaving the user with a really poor experience.

**Comment by mvrhov** [comment]
@kapowkimc WTF are they serious? Then this probably happens also if you copy paste the link via the skype (Skype tries to resolve the link to show a webpage preview)

**Comment by XWB** [comment]
You can override the controller as described in https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2106#issuecomment-212027852

**Comment by henrypenny** [comment]
I'm currently experiencing an issue with confirmation links (when provided with hrefs). When I view a confirmation email in a web client that previews links this has the side effect of actually confirming the user registration. So when I actually click the link I get token not found.

Is this something that can be handled by fos user bundle? Or does anyone know of a standard way to tell web clients not to preview a specific link?

**Comment by mablae** [comment]
@henrypenny Sorry, but did you even read this thread?

**Comment by henrypenny** [comment]
@mablae Yes I did.

@djardine makes the following statement: 

> As far as I can tell, what's really happening is that they're clicking the link more than once (I'm really just theorizing here since I don't know for sure) because when I check their account status in our database the "enabled" column has been set to "true" which indicates that they did successfully follow the link.

I'm suggesting a scenario where this appears to have happened but it in fact was the mail client causing the first 'click'.

I have been wrestling with this problem for a long time, and finally managed to figure out what was going on. It's impossible to reproduce on my localhost since webclients can't see the link to preview it.

I found this thread while searching for a solution. So I thought it would help others to share my situation and findings.

I also, believe it might have some bearing on whether this feature request has some validity. Or perhaps it suggests that a mechanism to bypass this issue might be required, ie. and two step confirmation. "Thank you for clicking the confirmation link, please click here to complete your confirmation" - kind of thing.

**Comment by mablae** [comment]
@mablae Yes I did.

Sorry, it seemed 'out of context' since overwriting the controller action was already mentioned as an solution above. 

> I also, believe it might have some bearing on whether this feature request has some validity. Or perhaps it suggests that a mechanism to bypass this issue might be required, ie. and two step confirmation. "Thank you for clicking the confirmation link, please click here to complete your confirmation" - kind of thing.

That would be a **true** solution. BTW:  What webclient causes the errors?

**Comment by henrypenny** [comment]
No worries @mablae :)

I'm currently testing with outlook.live.com.
I don't know how many other clients web based or otherwise would do this.
Previewing links seems to be more and more common, does it not?
