### ISSUE TITLE
Locked attribute removed in 2.0.0-beta1 version?

### ISSUE THREAD

**Issue by polantis** [FriendsOfSymfony/FOSUserBundle#2395]
Hello,

Why is this attribut removed? I am using it when some one has made a valid subscription but has made some suspicious activities on my website.  I need two fields: enable and locked

Do i have to create a new islocked function in my user class?

If i look at the user entity, it is not really usable..:
<code>
    public function isAccountNonLocked()
    {
        return true;
    }
</code>

Thank you,

Regards,

Guillaume

**Comment by stof** [comment]
if your project need it, you can add this field in your own child entity (and overwrite the Symfony interface method ``isAccountNonLocked()``).

The property was removed of the bundle because the bundle itself was not providing any feature based on it, and was enforcing a specific implementation of ``isAccountNonLocked()``, which was not flexible enough for some users, and which required an unused DB field for others. So we went the simplication way: not providing any field for it by default, and letting projects needing it implement it the way the want.

**Comment by XWB** [comment]
See above.
