### ISSUE TITLE
PHP 7.1 A non-numeric value encountered

### ISSUE THREAD

**Issue by JulienItard** [FriendsOfSymfony/FOSUserBundle#2442]
Hi,

i'm trying to update my FOSUser bundle `dev-master` but I have error `A non-numeric value encountered`. I'm using the new PHP 7.1

Thanks
Julien

**Comment by XWB** [comment]
In what file did you encounter this error?

**Comment by JulienItard** [comment]
![capture du 2017-02-14 15-31-17](https://cloud.githubusercontent.com/assets/1370893/22933074/a485b606-f2ca-11e6-83ac-12f35604d75e.png)

**Comment by stof** [comment]
this is an error in composer itself (which has been fixed in the snapshot version of composer already btw), not in the bundle code. Your screenshot is taken when executing composer, not when executing the bundle

**Comment by JulienItard** [comment]
i'm running last Composer version and this bug appears only when I try to update FOSUser bundle.

**Comment by stof** [comment]
you are running the latest composer *stable* version. I said it is fixed in the *snapshot* version (i.e. the version updated at each commit in the master branch).

And for the bug, it appears when you update a package with modified files in it. The fact that this happens only for FOSUserBundle in your project is not something coming from us.
