### ISSUE TITLE
Guest Accounts with Password = NULL ?

### ISSUE THREAD

**Issue by StefanGla** [FriendsOfSymfony/FOSUserBundle#2649]
Hello,

I've overwritten the password-column in my user entity with nullable = true. Is it an security issue, when having enabled or disabled user-accounts without any password (the password is always a null value)?

**Why I need that?**
I'm writing an ecommerce solution and I want to be able to create/update user-accounts without having any passwords, when users generates new orders in the store (I always have the users email-address for the entity).

When the users later come back to the store and would like to create a "real" password protected account, I would like to re-register the user with a custom password.

Any comments on that?

**Comment by girayk** [comment]
If you make user without password its can possible to login with only email address,
My suggestion is to create the random password to Guess users and add a role to GUESS_ROLE and when GUESS wants to register, send them to complete registration mail, which is similar to forget my password mail and with that way you can validate email address are as well.

**Comment by MarvinCourcier** [comment]
Hello @StefanGla i too do create an account when the user is purchasing.
What you can do is once the user bought your item you could create an even that would send him a link in order to confirm his account. This link would lead him to set his password.
If the user bought your product he is already interested and engaged, so more likely to click and confirm his account
