### ISSUE TITLE
non-existent service "templating".

### ISSUE THREAD

**Issue by emulienfou** [FriendsOfSymfony/FOSUserBundle#2679]
**Symfony version**: *4.0.2*

**Symfony FOSUserBundle versions**: *"friendsofsymfony/user-bundle": "dev-master"*

friendsofsymfony/user-bundle dev-master 5d1c3ff Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:
1. Simply installing the FOSUserBundle for Symfony 4 by doing a `composer require friendsofsymfony/user-bundle:dev-master`
2. Get the next exception message: **The service "fos_user.mailer.default" has a dependency on a non-existent service "templating".**

**Problem location**:
* The problem seems to be at the line *17* at: `<argument type="service" id="templating" />` in the file: */vendor/friendsofsymfony/user-bundle/Resources/config/mailer.xml*
* The service can only be one of those:
  * `<argument type="service" id="templating.engine.twig" />`
  * `<argument type="service" id="templating.engine.php" />`
  * `<argument type="service" id="templating.engine.delegating" />`

> However, by choosing one of those services, the exception is not removed!

Thanks for your help!

**Comment by emulienfou** [comment]
After some search, the next services:
* `<argument type="service" id="templating.engine.twig" />`
* `<argument type="service" id="templating.engine.php" />`
* `<argument type="service" id="templating.engine.delegating" />`

seems to haven't a public visibility to be accessed to.

**Comment by fa-dd** [comment]
I got the error away by adding the following lines to my `config/packages/framework.yaml` file without further changes to other files.

```
templating:
    engines:
        twig
```

I then ran my developing site, went to /register, registered a new user and activated it manually afterwards (as the email cannot be sent from my development area) without facing any issues.

**Comment by XWB** [comment]
Templating service should be available in Symfony. If not, please install `symfony/templating`.

**Comment by saravanakumargn** [comment]
```
framework:
    templating:
        engines: ['twig', 'php']  
```

**Comment by eureka2** [comment]
As @tacman says, "framework.templating" is deprecated since Symfony 4.3.

The templating (`Symfony\Bundle\FrameworkBundle\Templating\EngineInterface`) is used by the class "`FOS\UserBundle\Mailer\Mailer`".

Until the mailer of FOSUserBundle is rewritten with the new [mailer component](https://symfony.com/doc/current/mailer.html) added in Symfony 4.3, it is possible to configure FOSUserBundle to use the class "`FOS\UserBundle\Mailer\TwigSwiftMailer`" to work around this issue.
To do this, add the 2 lines:
```
     service:
         mailer: fos_user.mailer.twig_swift
```
at the end of the file "`config/packages/fos_user.yaml`"

you will be able to delete the lines:
```
framework:
     templating:
         engines: ['twig', 'php']
```
in the file `"config/packages/framework.yaml"`
