### ISSUE TITLE
$this->container is null in v2.1.1

### ISSUE THREAD

**Issue by picks44** [FriendsOfSymfony/FOSUserBundle#2737]
When updating from `friendsofsymfony/user-bundle v2.0.2` to `v2.1.1` with `Symfony 2.8.x`, I get the following errors on all the bundles routes:

`Error: Call to a member function has() on null`

```
public function getUser()
 {
        if (!$this->container->has('security.token_storage')) {
            throw new \LogicException('The SecurityBundle is not registered in your application.');
        }
}
```

Basically, the container is not callable.
I went through the bundle documentation again to see if something has changed but my config follows the rules and if I go back to v2.0.2, this problem disapears.

Any clue?

**Comment by MlleDelphine** [comment]
I have a pretty same issue.

I updated yesterday and now I am unable to override `LoginAction` (SecurityController).

FOSUser SecurityController is now called isntead of mine and obviously breaks my code (I pass some new variable, `registerForm`, to Twig view) .
`
Variable "registerForm" does not exist.`

**Comment by stof** [comment]
@MlleDelphine the upgrade file mentions that the way to override controllers changed in 2.1 as we changed the way we reference them in the routing. If you want to override things, the safer way is to override both the route and the controller (making your own route reference your own controller), because we don't provide BC on the override of the controller alone (which forbids changing the way we reference them in our routes, and relies on a legacy Symfony feature anyway). This is a totally different issue than the one reported here.

Regarding the issue about the container being null, this looks like Symfony 2.8 does not behave the same than Symfony 3.x regarding injecting the container into controllers defined as services, because Symfony 3.x does not have this bug.

**Comment by stof** [comment]
@picks44 I open a PR (linked just above) which should fix your issue. Can you try the patch ?

**Comment by picks44** [comment]
@stof thanks, I've seen the PR has been merged, can I update the bundle safely now?

**Comment by stof** [comment]
@picks44 it is not yet released, so you would have to update to the dev version. The update will come soon.

**Comment by picks44** [comment]
@stof OK I'll wait then, thanks!

**Comment by Ecureuilvirtuel** [comment]
@stof thx

**Comment by picks44** [comment]
Hi @stof, any news about the release?

**Comment by stof** [comment]
2.1.2 is released now

**Comment by picks44** [comment]
Awesome, thanks!

**Comment by Ecureuilvirtuel** [comment]
Thx @stof
