### ISSUE TITLE
Docs/example for overriding FOSUserbundle validation criteria in Symfony v3.4/4 -- since bundle inheritance has been deprecated?

### ISSUE THREAD

**Issue by hal869** [FriendsOfSymfony/FOSUserBundle#2773]
FOSUser docs

  https://symfony.com/doc/master/bundles/FOSUserBundle/overriding_validation.html

address

**_Overriding Default FOSUserBundle Validation_**
> The Resources/config/validation.xml file contains definitions for custom validator rules for various classes. The rules defined by FOSUserBundle are all in validation groups so you can choose not to use them.

There's no mention of overriding/changing the validation criteria.

Fosuser apparently used to allow bundle-inheritance based override

**_FOSUserBundle - Validation for username, password or email fields_**
https://stackoverflow.com/a/16704124

In Symfony 3.4 bundle inheritance was, in general, deprecated, 

_**New in Symfony 3.4: Deprecated bundle inheritance**_
https://symfony.com/blog/new-in-symfony-3-4-deprecated-bundle-inheritance

There it says

> "Validation: (override) not possible unless the bundle provides validation groups."

Symfony4 docs,

**_Validation Metadata_**
https://symfony.com/doc/current/bundles/override.html#validation-metadata

state

> Symfony loads all validation configuration files from every bundle and combines them into one validation metadata tree. This means you are able to add new constraints to a property, but you cannot override them.
> 
> To overcome this, the 3rd party bundle needs to have configuration for validation groups. For instance, the FOSUserBundle has this configuration. To create your own validation, add the constraints to a new validation group:
> ...
> Now, update the FOSUserBundle configuration, so it uses your validation groups instead of the original ones.

Is there any doc/example for FOSUSer + SF4 of specifically

(1) changing FOSUser form validation criteria (e.g username & password minimum lengths, & allowed/required characters),

(2) updating the FOSUserBundle to use such changes?

**Comment by nicolas-lesage** [comment]
@hal869 Since you closed the topic, did you find a solution to this problem?

I'm trying to get rid of my child UserBundle to migrate SF3.4 + FOSUserBundle to SF4, but the validation file I create in <myProject>/app/Resources/config/validation.xml is not taken into account (I use annotations for this bundle and don't know if both annotations and xml are compatible).

I have `validation: { enable_annotations: true }` in my config.yml and I have read [here](https://stackoverflow.com/questions/12367791/symfony2-how-to-load-validation-yml) (last comment) that it should take into account both annotations and xml/yml.

Any help would be appreciated :)
