### ISSUE TITLE
Upgrade password to a new (better) encoder on the fly

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSUserBundle#2788]
**Symfony FOSUserBundle versions**:

2.1.2

**Describe the feature**:

Encoders are meant to be changed. Previously best practice, `bcrypt` is to be replaced with `argon2i`.

But, if you replace the encoder in config, your users are left unable to login until they reset the password (or I'm missing some key part of the puzzle).

It would be nice if we could select the best available encoder once our infra supports it and have the system upgrade the passwords as the users log in.

Since the hashes actually include the encoder, why not use it?

ie.
```
# bcrypt, upgrade to argon2i on login
$2y$13$mPOLriX7szCVZx3glboORuyDaO6DbFfJlv6kEwkVSPZ3vIpZ1Wx0a
$2y$13$M8DU4u/b7oxju7GoukwaSOepBloh.YcnqzwvKIBPD3/2HRbAa6uPe

# argon2i, leave as-is
$argon2id$v=19$m=65536,t=2,p=1$JYhg5i+XEf54LRqAyPxb+Q$/Rt4toDMfFE8YjrngZN6cszds4KliiySB4U30WG+Zps
```

**Comment by stof** [comment]
Symfony already has a feature allowing you to change encoder on a per-user basis rather than on a per-class basis. This is not specific to FOSUserBundle. And this is what allows to keep users using bcrypt to login even after you switch to argon2i for newer users.

The way to detect which encoder is currently used is not something FOSUserBundle can implement for you, because it depends on the ones you use (bcrypt and argon2i can be identified from the hash, but older Symfony encoders cannot), so it may require storing an additional property in the User class depending on the need (in my project, I had to add such a property for instance, when migrating to bcrypt).
Thus, to be able to upgrade to a new hashing algorithm, you would have to be able to make your implementation return a different encoder name *before* the new hash is set (at the time you decide to upgrade), which might also be hard to achieve without a dedicated property.

The PasswordUpdaterInterface allows you to hook into FOSUserBundle to ensure that anytime the user changes their password (change password UI, password resetting UI, your own UI setting the `plainPassword` property and saving the user), the new one gets the new hashing algorithm. See https://gist.github.com/stof/cda5cad681e4fef092631a7a93c40ef7 for an example.
I don't yet have an example hooking into Symfony itself to perform this upgrading on login (which is a time where we can get this plain password again). This is on my TODO list though. I will comment again when I have the code.

I'm not sure this feature belongs to FOSUserBundle though, as the way to store the encoder will depend on the needs and you might not want to have a field in the DB in case your project can avoid it.
