### ISSUE TITLE
[Edit form] User is persisted even with invalid data

### ISSUE THREAD

**Issue by lobodol** [FriendsOfSymfony/FOSUserBundle#2822]
Hello FOS community,

I face something strange with the UserBundle. Here are the details:

Configuration:
* Symfony: 2.8
* FOSUserBundle: master
* php: 7.1
* OS: Linux Mint 
* Apache: 2.0
* MySQL: 5.7

I created a new SF2.8 project and installed FOSUserBundle following the official documentation.

Moreover, I added an event subscriber doing an `EntityManager::flush()` on each Kernel Request (it creates & persists a new entity, not related to the User entity).

Test procedure:

1. Create a user with CLI
```
php app/console fos:user:create
```

2. Log in and go to the profile edit form.

3. Type a username only composed of spaces and submit.

The validation fails and an error message is displayed "Please enter a username." as expected.
But the modification **is** persisted in database : 

```sql
SELECT * FROM user
```

```
+----+----------+--------------------+------------+-----------------+---------+------+--------------------------------------------------------------+---------------------+--------------------+-----------------------+--------+
| id | username | username_canonical | email      | email_canonical | enabled | salt | password                                                     | last_login          | confirmation_token | password_requested_at | roles  |
+----+----------+--------------------+------------+-----------------+---------+------+--------------------------------------------------------------+---------------------+--------------------+-----------------------+--------+
|  1 |          |                    | foo@foo.fr | foo@foo.fr      |       1 | NULL | $2y$13$y6gpr4jHQtNYi8ehRASFUedaZIPv7I1u7Z4AXZu7.j5Dhl2itOYQi | 2018-07-23 10:59:33 | NULL               | NULL                  | a:0:{} |
+----+----------+--------------------+------------+-----------------+---------+------+--------------------------------------------------------------+---------------------+--------------------+-----------------------+--------+
```

If I disable my event subscriber responsible of the `EntityManager::flush()`, the modification is not persisted anymore.

Do I misunderstand something ?
Is it a bug in the bundle ?
Why the User entity is persisted whereas it should not ?

Regards,

**Comment by lobodol** [comment]
Any news about this issue ?

**Comment by Devtronic** [comment]
Please post the content of your edit method.

**Comment by stof** [comment]
Well, if you have an event listener forcing a flush, you are creating the bug. As soon as an object is known by Doctrine, changes in it will be saved on flush. And during edition, the object being edited is already known by Doctrine, as it was loaded from the DB.

If you want to always do flushes automatically in a listener and avoid getting issues for invalid objects, you would need to use the explicit change tracking feature of Doctrine (which would consider changes only for objects on which `persist` was called again).
FOSUserBundle is compatible with this feature (we always call `persist` in our own code wanting to save changes, even on edition), but you have to enable it in your User entity if you want to use it.

I'm closing this issue, because the bug is not in FOSUserBundle, but in the way you use Doctrine in your project.

**Comment by lobodol** [comment]
Thank you for your reply.

I believed  FOSUserBundle did not call `persist` until the User entity is not valid thus, I though I could call `flush` without problem.

Indeed, it's my way of use of Doctrine that creates the bug.
Here is a link about [Doctrine's change tracking policies](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/change-tracking-policies.html) for those who are interested.

Regards,

**Comment by stof** [comment]
@lobodol we don't call `persist` if the object is not valid. But during edition, calling it is not needed for Doctrine when using implicit change tracking.
