### ISSUE TITLE
No Longer Maintained Message On Documentation

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#2874]
This isn't a bug report or the like, this is simply a reporting of the link at the documentation states:

>WARNING: You are browsing the documentation for version master which is not maintained anymore. If some of your projects are still using this version, consider upgrading.

https://symfony.com/doc/current/bundles/FOSUserBundle/configuration_reference.html

https://symfony.com/doc/current/bundles/FOSUserBundle/index.html

Is this the actual case?

**Comment by mablae** [comment]
This looks like some kind of mistake to me. 

It seems the rendering of rst files puts that advice into the docs when rendering from an master branch since it is not contained in the master docs of this bundle. 

Folks are already asking about this issue on symfony-devs Slack - it is very confusing and should be solved asap.

**Comment by nehalist** [comment]
"Opened this issue on Nov 28, 2018"

No reply so far.

Guess this answers the question.

**Comment by Chemsmith** [comment]
@stof @XWB care to comment?

**Comment by xabbuh** [comment]
@javiereguiluz Can you have a look here?

**Comment by javiereguiluz** [comment]
Sorry for the lack of response. A few months ago we removed FOSUserBundle docs from symfony.com because we don't want to promote this bundle anymore. We told about this to one maintainer of this bundle so they can move the docs elsewhere. We haven't received any confirmation that this has been completed, so we haven't enabled the doc redirection yet from symfony.com to the new doc.

**Comment by XWB** [comment]
@Chemsmith I'm sorry but I'm not involved with symfony.com

**Comment by ProtonScott** [comment]
> Sorry for the lack of response. A few months ago we removed FOSUserBundle docs from symfony.com because we don't want to promote this bundle anymore. We told about this to one maintainer of this bundle so they can move the docs elsewhere. We haven't received any confirmation that this has been completed, so we haven't enabled the doc redirection yet from symfony.com to the new doc.

Just curious as to why, since you mentioned you don't want to promote it anymore. Is this going to happen to other 3rd party bundles that you have on the site too?

If you can't comment for some reason I understand, just seems like a natural question.

**Comment by Amunak** [comment]
@ProtonScott Maybe because this bundle is 1) not really necessary (it tries to be a all-in-one solution for user management in Symfony, but it's not very good at it when you can write it yourself easily) and 2) has been barely maintained for the past year or so.

Yes, it's technically compatible with SF4 but it hardly follows its practices anymore; there's no PHP7 strict types support, etc.

**Comment by ProtonScott** [comment]
@Amunak I can see that being the case then, of course. What this package should have is a deprecation notice (and/or be marked abandoned on packagist) and removed from the symfony site then. If applicable, a migration path should be announced.

This seems like it would be a win-win if this bundle is not going to be maintained anymore.

**Comment by Amunak** [comment]
I agree, that would indeed be sensible.

The migration path, I'm afraid, is to just go through the "regular" Symfony user management.

Basically you need to move all the properties and methods from FOSUserBundle's User entity into your own User entity (or at least those that are used by your code OR those that are in the UserInterface or AdvancedUserInterface) along with mappings and validation constraints. Additionally you need to create a login controller, which also means you may need to create (or copy from FOS) a llogin form template and such.

If you take care while doing this you can do it seamlessly though without changing much in your application. The "worst" I had to do was to create my own UserManager with a handful of methods that my code uses, and replacing `use`s of FOS' version with mine.

**Comment by ProtonScott** [comment]
@Amunak 

To be perfectly honest, I walked away from the FOSUserBundle shortly after opening this issue (for unrelated reasons, I found it was not befitting of my needs).

**Comment by Dranac** [comment]
It could be nice to have some information about the situation on README or in the description of the repo.

**Comment by Artusamak** [comment]
This bundle is unmaintained, if you are looking for alternatives, please read this comment that brings context and info to your potential alternative to FOSUserBundle. 
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2943#issuecomment-573042234
