### ISSUE TITLE
Package extends deprecated controllers

### ISSUE THREAD

**Issue by archi-tektur** [FriendsOfSymfony/FOSUserBundle#2905]
Screenshot says more than thousands words. Your package extends deprecated classes. Please fix it fast.

![image](https://user-images.githubusercontent.com/26973065/56677016-dcc20400-66bf-11e9-8f6f-093795074e07.png)

**Comment by spyridonas** [comment]
It's already "fixed"
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2883
I don't know when it will be released though, i was searching for the same thing as you.

**Comment by stephanvierkant** [comment]
Please include information about your set up (version of Symfony, this library, etc.). Are you using `dev-master` or a stable version? And please do some research before opening an issue, as the problems are already fixed months before you opened this issue.

> Screenshot says more than thousands words.

But it makes searching for relevant issues impossible. Please use texts instead of screenshots. We can't copy-paste the logs (message, filename, etc.) to help you with this problem.

> Please fix it fast.

This is an open source project. Maybe it's the language barrier that makes this comment a bit rude (I'm not a native English speaker either ánd Dutch, so I sometimes have that problem), but you're not a customer who can demand something. Please be friendly to the maintainers or try to fix the problem yourself by opening a Pull Request.

**Comment by stof** [comment]
Fixed in #3016
