### ISSUE TITLE
Is this bundle still maintained?

### ISSUE THREAD

**Issue by markitosgv** [FriendsOfSymfony/FOSUserBundle#2917]
Is this bundle still maintained? Is there any other alternatives to manage users?

**Comment by enrico69** [comment]
I am still interested to fork it to implement all the S4 features and make it ready to S5.
However it is a lot of work for one person, so if you want to contribute, let's go :) 

There is a lot to do, especially since the arrival of Symfony 4.3 which deprecrated the templating bundle. We also would need to replace the SwiftMailer vendor by the Symfony Mail component.

**Comment by ProtonScott** [comment]
I just wanted to link in the discussion we had about this previously in #2874 

It doesn't appear this is going to see any ongoing development, from the looks of it.

**Comment by core23** [comment]
If anyone is still interested in this, I made a hard fork with some minor cleanups: https://github.com/nucleos/NucleosUserBundle
