### ISSUE TITLE
Composer doesn't download right version 2.1.2

### ISSUE THREAD

**Issue by Viperium** [FriendsOfSymfony/FOSUserBundle#2920]
Bug report composer. 

**Symfony version v4.3.1**
**FOSUserBundle version 2.1.2**:
composer info: friendsofsymfony/user-bundle v2.1.2  Symfony FOSUserBundle

**Description of the problem**:
The updates that were made in v2.1.2 are not being installed by composer. In composer it says it is using v2.1.2 but its not. For example TreeNode problem still exists. 

Expectation changes in master 2.1.2 of FOSUserBundle. But composer says its v2.1.2 but it is not.

**Steps to reproduce**:
 1. Install new version of Symfony 4.3.1 - composer create-project symfony/website-skeleton
 2. Install FOSUserBundle v2.1.2 - composer require friendsofsymfony/user-bundle
 3. Configure FOSUserBundle route, security and mailer_user in .env
 4. Error:

![image](https://user-images.githubusercontent.com/48511875/60171231-7b76f800-980a-11e9-904e-6ac41d0dc464.png)

 5.  Remove line 16 of vendor/friendsofsymfony/user-bundle/Resources/config/Mailer.xml 
<argument type="service" id="templating" />

 6. Make new controller: bin/console make:controller HomeController
 7. Edit src/Controller/HomeController.php line 11 * @Route("/", name="home")
 8. Go to Profiler
 9. Deprecated errors: TreeNode which was fixed in v2.1.2

![image](https://user-images.githubusercontent.com/48511875/60175614-58e9dc80-9814-11e9-87e0-1deb18fe0cde.png)

**Comment by richardhooper** [comment]
I came here looking to see if anyone had reported this!  I'm having a similar issue.  Similar because my vendors FOSUserBundle code seems to be old, not because I'm seeing the same exception; in my case it's the behaviour you get when a registration confirmation link is followed twice that is wrong, it should redirect to the login page, but instead I'm getting an exception.

The dist link referenced for FOSUserBundle's in my composer.lock is https://api.github.com/repos/FriendsOfSymfony/FOSUserBundle/zipball/1049935edd24ec305cc6cfde1875372fa9600446.  Downloading that file gives me a zip containing the old code, not what is tagged 2.1.2 on GitHub,.

**Comment by richardhooper** [comment]
On further investigation, it looks like my issue is "correctly" not in `2.1.2`, because it was silently removed from `master` in commit `a44ee612b04d3af72ab068f98d744a41e10f2814` on 2018-02-16, then `2.1.2` was tagged on 2018-03-08, then the change was redone on 2018-04-06 in commit `070c860b268df7be98fb9233ff7e8bc2e3b8e19d`, but that's yet to be tagged.  I haven't checked the specific issue raised here, but I wouldn't be surprised if something similar hasn't happened.

**Comment by lajosmakaiDev** [comment]
any update?

**Comment by Viperium** [comment]
4 months later and still not even assigned. I just want those deprecation errors gone and I dont want to go to a dev branch on this project!

**Comment by scherwinsalehi** [comment]
Please update the dist, we are forced to add  "minimum-stability": "dev", to our composer.json

**Comment by stof** [comment]
Closing as 2.2 has been released
