### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symfony_website.fos_user_user' doesn't exist

### ISSUE THREAD

**Issue by Kioshai** [FriendsOfSymfony/FOSUserBundle#334]
Hi,

I have some troubles with FOSUserBundle. I working on a Support Ticket classic, and I want my ticket to be owned by only one user. So I tried to make this relationship like below :

$username = $this->container->get('security.context')->getToken()->getUsername();
        $em = $this->getDoctrine()->getEntityManager();
        $userEntity = $em->getRepository('FOSUserBundle:User')->findOneByUsername($username);

As you can see, when I try to find user with this code, I have that error : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symfony_website.fos_user_user' doesn't exist.

However, the table name should be symfony_website.fos_user ... So I'd like to know how avoid this error, and how can I recover my user name properly ?

Thanks.

**Comment by mohamedaymenkarmous** [comment]
I have encountered this kind of problem
it looks like magic.
It happened to me when I created my database the first time with the command:

    php bin/console doctrine: database: create
    php bin/console doctrine: schema: update


Since that time the name of the database, the new attributes and new annotations could never be considered
I noticed this when I changed the name of the database in the file MyBundle/Entitiy/User.php
The problem persisted even after I re-created the database and after clearing all caches and after deleting all cookies:

    rm -R var/logs/*
    rm -R var/cache/*
    php bin/console cache:clear
    php doctrine:generate:entities MyBundle

And when I did a search with the command

    -rnw grep '/path/to/my/project/' -e "old_name_of_the_table"

I found nothing
Well the problem was found in the file:

    app/config/config.yml

Exactly here:

    doctrine:
        # [...]
        orm:
                # [...]
                query_cache_driver: apc
                metadata_cache_driver: apc

Indeed, many developers uses APC as a best accelerator so I used it without documentation.
So you have to disable the APC during development to reactivate it at the end.

I told you this story to transmit it if someone else has found the same problem
