### ISSUE TITLE
Multiple user types

### ISSUE THREAD

**Issue by kemalayaz** [FriendsOfSymfony/FOSUserBundle#534]
Hi,

I think fosuserbundle does not have multiple user type support. Is it easy to add this support to bundle. I saw a few suggestions like creating another kernel and registering the bundle with different parameters. I could not understand how to do it and is it the best way?

Thanks,
Kemal

**Comment by warslett** [comment]
RollerworksMultiUserBundle is now discontinued and PGUXMultiUserBundle does not yet support symfony 3 or fos user 2 so those options won't work. This is the second project in a row where I have run into this problem. Setting different roles for different types of user is not always sufficient because different user types might have different associations in your business model.

For example, I have a ClientUser who has a relationship with a Client entity and I have a ParticipantUser who has a relationship with a ParticipantGroup Entity. This limitation means that I can't implement this model properly. Instead I have to have a single User object which has both a ParticipantGroup association AND a Client association and one of the two is always null depending on the type of User. I also end up having to use ugly control logic all the way through my code to distinguish the behaviour of different user types instead of doing it in an object oriented way. I'm also concerned that this will lead to data inconsistencies eg. what happens if a ClientUser accidentally gets associated with a ParticipantGroup?

**Comment by sstok** [comment]
@warslett I highly recommend to stop using the FOSUserBundle if you need handle more then one user type. Build your own specific implementation, one per user type.

https://jolicode.com/blog/do-not-use-fosuserbundle
http://elnur.pro/use-only-infrastructural-bundles-in-symfony/

Trying to shoehorn the FOSUserBundle into support multiple user types is really complex and error prone, which is also the reason why I decided to discontinue the RollerworksMultiUserBundle.
I'm not using the FOSUserBundle anymore and the maintenance cost were to high.

**Comment by dramentol** [comment]
I use FOSUserBundle with multiple user types through inheritance and it's perfectly fine.

**Comment by gpapin** [comment]
I require different type of users too, and my approach was to use inheritance as @dramentol suggested. However it's not mentioned in the doc anywhere so I wonder if it's something production ready or more of a hack ?

I have 2 class AppUser and Reseller (reseller extends AppUser) 
but then doctrine duplicates all the fields from the user table to the reseller table and then everything gets confused when I try to load the object... The application thinks my reseller is just a user so the getCompany defined on the reseller class doesn't work for example. 

Some guidance on how to implement proper inheritance would be very useful. Meanwhile I'll have to deal with a 1to1 mapping with reseller<-> user

**Comment by dramentol** [comment]
Hi @gpapin,

To your first question, I don't think it's a hack, I think it is completely valid.

About your issue, sounds to me your inheritance is not well configured. Can you post your code?



Enviat des del meu iPhone

El 7 abr 2017, a les 18:59, gpapin <notifications@github.com> va escriure:

**Comment by nmihaylov** [comment]
Hey @gpapin,

I have a project where I need to use multiple user types so could you please share more details/code/guidelines on how did you setup the multiple user types through inheritance in with FOSUserBundle?

**Comment by Gog0** [comment]
@dramentol I'm working on this (using FOSUser 2.*). Could you explain a bit more about inheritance to achieve this?

What would be the best-practice today on this topic? Does anyone now if FOSUser made any imrovements on this subject? I don't see anything in the documentation.

**Comment by stof** [comment]
@Gog0 From the FOSUserBundle PoV, things have not changed. Supporting multiple user classes is not in our scope.

**Comment by diimpp** [comment]
For anyone, who is really needs multi-user support, checkout Sylius User Bundle/Component. It allows to create as many users out of the box as needed.
