### ISSUE TITLE
$user->getPlainPassword()

### ISSUE THREAD

**Issue by freenando** [FriendsOfSymfony/FOSUserBundle#998]
Hello, I am doing this:

//shows encrypt password 
echo $user->getPassword();
//set encrypt password to plaintext
echo $user->setPlainPassword($user->getPassword()); 
//why shows username ?????
echo $user->getPlainPassword();       

Last line of code shows me username instead plain password? What am i doing wrong?

**Comment by Saint-Cyr** [comment]
Hi guys !
I've the similar problem. I'd like get the plainPassword from the DB in order to generate to the end user by SMS but  $user->getPlainPassword() return NULL. in the following method

`public function showAction(User $user)
    {
        $deleteForm = $this->createDeleteForm($user);
        var_dump($user->getPlainPassword());exit;
        return $this->render('user/show.html.twig', array(
            'user' => $user,
            'delete_form' => $deleteForm->createView(),
        ));
    }`

**Comment by stof** [comment]
you cannot get it from the DB. We don't store the plain text password (this would be a major security issue)

**Comment by Saint-Cyr** [comment]
Thank @stof  for your support.
 So if I understand well with FOSUserBundle after the registration of a user, we cannot (within a controller) get the password in plain text ?? I just though that is what the method getPlainPassword() suppose to do I'm wrong ? please how can I do that : After the registration I just want to get the password in plain text from a controller's action for a given user so that I can send it to him by SMS (for he cannot read the encrypted one in the DB) Exple:  

`/**
 * User controller.
 *
 * @Route("/user")
 */
class UserController extends Controller
{
    public function generatePassword(User $user)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('UserBundle:User')->find($user->getId());
        
        if(!$user){
            throw $this->createNotFoundException('User entity not found.');
        }
        
        $password = $user->getPlainPassword();
        //...Send the password through the SMS API    
    }
}`

**Comment by stof** [comment]
> After the registration I just want to get the password in plain text from a controller's action for a given user so that I can send it to him by SMS (for he cannot read the encrypted one in the DB

being able to do that means that you have a huge security hole in your system, as you are able to know the plain text password.

FOSUserBundle cannot do it, because it does not store an encrypted password, but a hashed password. See http://stackoverflow.com/questions/4948322/fundamental-difference-between-hashing-and-encryption-algorithms if you don't know the difference.

If you have a need to send a password by SMS at some point, you will need to generate the plain text password at this point (so that you know it), and save its hash in the DB (this can be done by calling ``$user->setPlainPassword($newPassword);`` and then ``$userManager->updateUser($user);`` as FOSUserBundle takes care of hashing the password during the call to ``updateUser``)

**Comment by Saint-Cyr** [comment]
Ha I get it and I see the professionalism ( just I didn't get it for you and I don't have the same level). However, what I plan to do is to generate the password just before a do $manager -> updateUser($user)

**Comment by stof** [comment]
@Saint-Cyr in your code snippet above, there is nothing generating a new password. there is only code reading the user from the DB.

**Comment by Saint-Cyr** [comment]
I meant not for the above code but after the submission of the form

**Comment by stof** [comment]
Well, as I said, the **only** time you can have the plain password is at the time it is generated. You cannot access it in a separate controller called later (and this will be true for any secure architecture, as it is one of the requirements to make it secure). You must take this into account when architecturing your system sending SMS with the password.

On a side note, you should be aware that SMS is not a secure comunication channel, so any password sent inside a SMS is a leaked password. So you should better rethink the system (this is why our password resetting feature does not send a new password in the email but a temporary link allowing to choose the new password btw)

**Comment by Saint-Cyr** [comment]
Thank you so much for clarification I take note of it seriously !
